### ISSUE TITLE
Bold "asynchronous I/O is already possible"

### ISSUE THREAD

**Issue by delbonis** [rustasync/areweasyncyet.rs#11]
This would make it more obvious that it's already possible since at first glance you see

>async syntax and blockers
>
>async/await syntax not stabilized yet

which might make it seem like it's "not possible" or "not easy" if you fail to register the word "syntax" entirely.

**Comment by upsuper** [comment]
For those who cannot recognize the word "syntax", I don't think marking that sentence bold really helps...

Also, without `async` syntax, some asynchronous scenarios are indeed harder to do than they could be, so making it seem like it's "not easy" isn't something completely wrong per se.

This site is mainly built for people to follow progress of Rust `async` syntax. Are there many people outside using this site to judge Rust's async IO support?

**Comment by delbonis** [comment]
>Are there many people outside using this site to judge Rust's async IO support?

Oh yes.  One of the main reasons why people choose to use Go is because async IO is just "a part of the language" due to its greenthreading model (and unfortunately that's the only other good thing about it).  I'm certain that there exists people that use Go (despite its many flaws) because what's possible with Rust's async libs isn't as plainly advertised everywhere right now.

**Comment by upsuper** [comment]
I'm not fully convinced... but we can see.

Fixed in 0fd1d1eb42d1224267bcd4d1ada07ed14ece4bb6.
