### ISSUE TITLE
Add Generators to the extensions section?

### ISSUE THREAD

**Issue by nugend** [rustasync/areweasyncyet.rs#17]
Just that. It typically gets talked about as an extension of what's being done with async.

**Comment by upsuper** [comment]
Any link about this?

Personally I'm not convinced that generator is an extension of async. Async function may have been able to reuse generator's mechanism, since they are conceptually similar. However, I don't think it is possible on the language level to utilize async fn as generator.

**Comment by nugend** [comment]
Alright, just thought it might bear mentioning because of the conceptual similarity. Please close if not pertinent.

**Comment by upsuper** [comment]
Okay, let's close this issue for now.

Given withoutboats' latest blog post (to be added to the post list soon), it is possible that there is going to be a combination of generator and async function to form an ergonomic way for stream (similar to JavaScript's `async function*()` I would guess). If that becomes a formal plan, generator would likely be tracked as a dependency of that feature.
