### ISSUE TITLE
Set up GitHub releases

### ISSUE THREAD

**Issue by TomasHubelbauer** [rustasync/areweasyncyet.rs#18]
I'd like to propose that GitHub releases are used and cut each time a new version of the site goes up so that people can select Watch Releases and GitHub and subscribe this way.

**Comment by upsuper** [comment]
It's not clear when should we have a new release, though. There can be general maintanence pushes like updating page gen code, updating dependencies, which definitely should not trigger a new release.

That basically means we would need some extra manual work to tag releases, which I'm kinda reluctant...

**Comment by TomasHubelbauer** [comment]
Personally I am cool with noise releases. It's still better than no releases IMO.

I would liken this to subscribing using the normal Watch. You see all issues, not just merged PRs. In this case you would see all deploys, not just content-change deploys. As easy to ignore as all the issues you see with normal Watch when you are only looking for merged PRs.

**Comment by upsuper** [comment]
Sounds good. I'll try to setup releases probably tomorrow.

**Comment by upsuper** [comment]
Alright... I setup a semi-automatic release, and I would just tag each content change manually, which is probably not too bad. I have a feeling that having CI automatically tagging and then doing release may be more complicated than it's worth.

**Comment by TomasHubelbauer** [comment]
Thanks for offering to do that manually! I agree with you that looking for an automated way to do this is a waste of time and I also wanted to save you work with everything goes style release cutting, but as long as you're willing to tag manually, that's the best option.
