### ISSUE TITLE
Filter out issues with "AsyncAwait-Deferred" label

### ISSUE THREAD

**Issue by Arnavion** [rustasync/areweasyncyet.rs#19]
Currently 23 of the 32 open "A-async-await" issues are also "AsyncAwait-Deferred". That label is for issues that are not expected to block `async-await` stabilization, so perhaps they should be filtered out?

**Comment by upsuper** [comment]
The issues listed there doesn't mean they necessarily block the issue. You can see that the stablized `impl Trait` still has lots of open issues listed there.

I guess we can probably do this to avoid some confusion, but I suspect that `AsyncAwait-Deferred` isn't meant to exist forever, i.e. it may be removed once `async`/`await` is stablized, which means the list may get populated again *after* stablization, which feels a bit weird.

Given these I tend to keep it as is for now.
