### ISSUE TITLE
Site needs updating

### ISSUE THREAD

**Issue by grahame** [rustasync/areweasyncyet.rs#28]
As noted on Hacker News, this site could use an update now that async is in stable :)

https://news.ycombinator.com/item?id=21473667
https://blog.rust-lang.org/2019/11/07/Async-await-stable.html

**Comment by Nemo157** [comment]
I've triggered a CI build, which I believe will update the site, but I'm not 100% familiar with the setup.

**Comment by Nemo157** [comment]
That appears to have worked :tada:

**Comment by upsuper** [comment]
Thanks!
