### ISSUE TITLE
Prominently track RFC 2071 (Named existentials and impl Trait variable declarations)

### ISSUE THREAD

**Issue by jimmycuadra** [rustasync/areweasyncyet.rs#8]
https://github.com/rust-lang/rfcs/pull/2071

This is a major component of the usability of async code in Rust that seems often left out of the discussion of the viability of Rust for async code. Without it you can't have an async fn or return an impl Trait type from a trait method. I think it should be added as one of the bullet points to the "async syntax and blockers" section.

Unfortunately its tracking issue (https://github.com/rust-lang/rust/issues/44686) was closed in favor of the larger https://github.com/rust-lang/rust/issues/34511 so I'm not sure how well its implementation and stabilization status can be tracked.

**Comment by upsuper** [comment]
I don't consider `async fn` in trait method an essential part of MVP of `async`, so I wouldn't add it to blockers. It can probably be listed in future extensions I guess.

**Comment by upsuper** [comment]
Added in 3ced57c43b5dfc66b28df87e266d72d7f34254cf.
